[package]
name = "pyhgvs2"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display"] }
lazy-regex = "3.4.1"
lazy_static = "1.5.0"
thiserror = "2.0.12"
